
package au.edu.unsw.soacourse.assign2.exactmatch;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-10T13:35:46.518+11:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "nullEntryFault", targetNamespace = "http://exactmatch.assign2.soacourse.unsw.edu.au")
public class NullEntryFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.assign2.exactmatch.ServiceFaultType nullEntryFault;

    public NullEntryFaultMsg() {
        super();
    }
    
    public NullEntryFaultMsg(String message) {
        super(message);
    }
    
    public NullEntryFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public NullEntryFaultMsg(String message, au.edu.unsw.soacourse.assign2.exactmatch.ServiceFaultType nullEntryFault) {
        super(message);
        this.nullEntryFault = nullEntryFault;
    }

    public NullEntryFaultMsg(String message, au.edu.unsw.soacourse.assign2.exactmatch.ServiceFaultType nullEntryFault, Throwable cause) {
        super(message, cause);
        this.nullEntryFault = nullEntryFault;
    }

    public au.edu.unsw.soacourse.assign2.exactmatch.ServiceFaultType getFaultInfo() {
        return this.nullEntryFault;
    }
}
