package au.edu.unsw.soacourse.assign2.addressservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-08T13:58:10.523+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "AddressService", 
                  wsdlLocation = "file:/Users/Leon/eclipse/workspace9322/rmsService/src/main/resources/wsdl/AddressService.wsdl",
                  targetNamespace = "http://addressservice.assign2.soacourse.unsw.edu.au") 
public class AddressService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://addressservice.assign2.soacourse.unsw.edu.au", "AddressService");
    public final static QName AddressService = new QName("http://addressservice.assign2.soacourse.unsw.edu.au", "AddressService");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Leon/eclipse/workspace9322/rmsService/src/main/resources/wsdl/AddressService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AddressService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Leon/eclipse/workspace9322/rmsService/src/main/resources/wsdl/AddressService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AddressService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AddressService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddressService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddressService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public AddressService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns AddressService
     */
    @WebEndpoint(name = "AddressService")
    public AddressService getAddressService() {
        return super.getPort(AddressService, AddressService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressService
     */
    @WebEndpoint(name = "AddressService")
    public AddressService getAddressService(WebServiceFeature... features) {
        return super.getPort(AddressService, AddressService.class, features);
    }

}
