package au.edu.unsw.soacourse.assign2.addressservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-08T13:58:10.515+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://addressservice.assign2.soacourse.unsw.edu.au", name = "AddressService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface AddressService {

    @WebResult(name = "validateAddressResponse", targetNamespace = "http://addressservice.assign2.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://addressservice.assign2.soacourse.unsw.edu.au/validateAddress")
    public ValidateAddressResponse validateAddress(
        @WebParam(partName = "parameters", name = "validateAddressRequest", targetNamespace = "http://addressservice.assign2.soacourse.unsw.edu.au")
        ValidateAddressRequest parameters
    );
}
