
package au.edu.unsw.soacourse.gnafaddressingservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-09-27T16:29:47.071+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "addressExistsFault", targetNamespace = "http://GNAFAddressingService.soacourse.unsw.edu.au")
public class AddressExistsFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType addressExistsFault;

    public AddressExistsFaultMsg() {
        super();
    }
    
    public AddressExistsFaultMsg(String message) {
        super(message);
    }
    
    public AddressExistsFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public AddressExistsFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType addressExistsFault) {
        super(message);
        this.addressExistsFault = addressExistsFault;
    }

    public AddressExistsFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType addressExistsFault, Throwable cause) {
        super(message, cause);
        this.addressExistsFault = addressExistsFault;
    }

    public au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType getFaultInfo() {
        return this.addressExistsFault;
    }
}
