package au.edu.unsw.soacourse.gnafaddressingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-09-04T21:06:19.646+10:00
 * Generated source version: 3.0.4
 * 
 */
@WebServiceClient(name = "GNAFAddressingService", 
                  wsdlLocation = "file:/Users/Dhruv/GitHub/cs9322-Prac/workspace/Asi1/src/main/resources/wsdl/GNAFAddressingService.wsdl",
                  targetNamespace = "http://GNAFAddressingService.soacourse.unsw.edu.au") 
public class GNAFAddressingService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://GNAFAddressingService.soacourse.unsw.edu.au", "GNAFAddressingService");
    public final static QName GNAFAddressingServiceSOAP = new QName("http://GNAFAddressingService.soacourse.unsw.edu.au", "GNAFAddressingServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/Dhruv/GitHub/cs9322-Prac/workspace/Asi1/src/main/resources/wsdl/GNAFAddressingService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GNAFAddressingService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/Dhruv/GitHub/cs9322-Prac/workspace/Asi1/src/main/resources/wsdl/GNAFAddressingService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GNAFAddressingService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GNAFAddressingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GNAFAddressingService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressingService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressingService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GNAFAddressingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns GNAFAddressingService
     */
    @WebEndpoint(name = "GNAFAddressingServiceSOAP")
    public GNAFAddressingService getGNAFAddressingServiceSOAP() {
        return super.getPort(GNAFAddressingServiceSOAP, GNAFAddressingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GNAFAddressingService
     */
    @WebEndpoint(name = "GNAFAddressingServiceSOAP")
    public GNAFAddressingService getGNAFAddressingServiceSOAP(WebServiceFeature... features) {
        return super.getPort(GNAFAddressingServiceSOAP, GNAFAddressingService.class, features);
    }

}
