
package au.edu.unsw.soacourse.gnafaddressingservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-09-04T21:06:19.634+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "returnPostcodeFault", targetNamespace = "http://GNAFAddressingService.soacourse.unsw.edu.au")
public class ReturnPostcodeFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType returnPostcodeFault;

    public ReturnPostcodeFaultMsg() {
        super();
    }
    
    public ReturnPostcodeFaultMsg(String message) {
        super(message);
    }
    
    public ReturnPostcodeFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public ReturnPostcodeFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType returnPostcodeFault) {
        super(message);
        this.returnPostcodeFault = returnPostcodeFault;
    }

    public ReturnPostcodeFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType returnPostcodeFault, Throwable cause) {
        super(message, cause);
        this.returnPostcodeFault = returnPostcodeFault;
    }

    public au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType getFaultInfo() {
        return this.returnPostcodeFault;
    }
}
