
package au.edu.unsw.soacourse.gnafaddressingservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-09-27T16:29:47.079+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "similarAddressesFault", targetNamespace = "http://GNAFAddressingService.soacourse.unsw.edu.au")
public class SimilarAddressesFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType similarAddressesFault;

    public SimilarAddressesFaultMsg() {
        super();
    }
    
    public SimilarAddressesFaultMsg(String message) {
        super(message);
    }
    
    public SimilarAddressesFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public SimilarAddressesFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType similarAddressesFault) {
        super(message);
        this.similarAddressesFault = similarAddressesFault;
    }

    public SimilarAddressesFaultMsg(String message, au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType similarAddressesFault, Throwable cause) {
        super(message, cause);
        this.similarAddressesFault = similarAddressesFault;
    }

    public au.edu.unsw.soacourse.gnafaddressingservice.ServiceFaultType getFaultInfo() {
        return this.similarAddressesFault;
    }
}
