package au.edu.unsw.soacourse.assign2.similarmatchservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-08T17:53:41.020+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://similarmatchservice.assign2.soacourse.unsw.edu.au", name = "SimilarMatchService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimilarMatchService {

    @WebResult(name = "validateSimilarMatchResponse", targetNamespace = "http://similarmatchservice.assign2.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://similarmatchservice.assign2.soacourse.unsw.edu.au/validateSimilarMatch")
    public ValidateSimilarMatchResponse validateSimilarMatch(
        @WebParam(partName = "parameters", name = "validateSimilarMatchRequest", targetNamespace = "http://similarmatchservice.assign2.soacourse.unsw.edu.au")
        ValidateSimilarMatchRequest parameters
    );
}
