package au.edu.unsw.soacourse.assign2.driverslicense;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-10-08T13:58:16.311+11:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://driverslicense.assign2.soacourse.unsw.edu.au", name = "DriversLicenseService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DriversLicenseService {

    @WebResult(name = "validateDriversLicenseResponse", targetNamespace = "http://driverslicense.assign2.soacourse.unsw.edu.au", partName = "parameters")
    @WebMethod(action = "http://driverslicense.assign2.soacourse.unsw.edu.au/validateDriversLicense")
    public ValidateDriversLicenseResponse validateDriversLicense(
        @WebParam(partName = "parameters", name = "validateDriversLicenseRequest", targetNamespace = "http://driverslicense.assign2.soacourse.unsw.edu.au")
        ValidateDriversLicenseRequest parameters
    );
}
